language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
# command to install dependencies
install:
  - pip install -r userservice/requirements.txt
  - pip install -r todoservice/requirements.txt

# command to run tests
script: nosetests
